[project]
name = "oarspac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.14"
dependencies = [
    "ospac @ git+https://github.com/hfpg2026/ospac@a7eb5db2d81a4ecad8b7ecc9dae26650675d5f78",
    "typer>=0.21.1",
]

[project.scripts]
oarspac = "oarspac.cli:app"

[tool.setuptools]
packages = ["oarspac", "oarspac.core", "oarspac.report"]

[tool.uv]
package = true
